######################## default configuration ####################
baseURL = "https://www.jarrettchristianflierl.com"
languageCode = "en-us"
title = "JCF | Jarrett Christian Flierl"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about/about"
  weight = 2

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about/about"
  weight = 2

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 4


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "Jarrett Christian Flierl"
author = "Jarrett Christian Flierl"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "305.902.7697"
email = "jcf@jarrettchristianflierl.com"
location = "Santa Monica, CA"
# copyright
copyright = "| @2019 [bigflexmedia](https://bigflexmedia.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join My Newsletter"
content = "Stay up to date with me! Jarrett Christian Flierl Updates to your email!"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/jarrett.flierl.39"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/jarrett_flierl"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/jarrettflierl/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/jarrett-flierl"

[[params.social]]
title = "tumblr"
icon = "ti-tumblr" # themify icon : https://themify.me/themify-icons
link = "https://jarrett-christian-flierl.tumblr.com/"
